defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
    TEST_OUTPUT_DIR: /tmp/planet4-docker
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:v0.3.11
  working_directory:  /home/circleci/app

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Version
          command: |
            docker --version
            docker-compose --version

      - checkout

      - run:
          name: Update build numbers
          command: |
            # Store current build number for future jobs
            mkdir -p /tmp/workspace/var
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
            ${HOME}/scripts/update-build-numbers.sh

      - run:
          name: Configure gcloud
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh

      - setup_remote_docker

      - run:
          name: Building platform containers on gcr.io
          command: |
            ./bin/build.sh -r
            rsync -avz . /tmp/workspace/src

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var
            - src

  test:
    <<: *defaults
    steps:

      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker

      - run:
          name: Run bats unit tests
          command: |
            cd /tmp/workspace/src
            BUILD_TAG="build-$(cat /tmp/workspace/var/circle-build-num)" ./tests/test.sh

      - store_test_results:
          path: /tmp/planet4-docker/merged

      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    <<: *defaults
    steps:

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure gcloud
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh

      - setup_remote_docker

      - deploy:
          name: Deploy tags on master branch
          command: |
            set -x

            export CIRCLE_BUILD_NUM=$(cat /tmp/workspace/var/circle-build-num)
            if [[ "${CIRCLE_BRANCH}" = "master" ]] ||
               [[ "$(cat /tmp/workspace/var/circle-branch-name)" = "master" ]]
            then
              cd /tmp/workspace/src
              ./bin/deploy.sh
            fi


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      # Only run deploy job for tagged releases, any branch
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
